### ISSUE TITLE
Insert crossfade generates an error in blender 3.2

### ISSUE THREAD

**Issue by kodiakcreativity** [GDQuest/blender-power-sequencer#463] opened 2022-06-19 19:08 UTC
select a strip and insert a cross fade using CTRL+ALT+c
An error results. with the release notes for Blender 3.2 it looks like several parameters were transitioned from int to float values to allow more smoothness in animations, I think this is the problem. the error states that it is expecting an int but found a float.

Python: Traceback (most recent call last):
  File "/programfiles/Blender/3.2/scripts/addons/power_sequencer/operators/crossfade_add.py", line 64, in execute
    self.offset_sequence_handles(context, s, s_to_offset)
  File "/programfiles/Blender/3.2/scripts/addons/power_sequencer/operators/crossfade_add.py", line 102, in offset_sequence_handles
    sequence_1.frame_final_end -= fade_offset
TypeError: bpy_struct: item.attr = val: MulticamSequence.frame_final_end **expected an int type, not float**

**Comment by NathanLovato** [comment] 2022-06-19 19:31
Already fixed, duplicate of #455

**Closed by NathanLovato** 2022-06-19 19:31 UTC
