### ISSUE TITLE
Import Local Footage doesn't import the first file in each folder

### ISSUE THREAD

**Issue by henriiquecampos** [GDquest/Blender-power-sequencer#344] opened 2019-04-06 15:44 UTC
Whenever I import files using `Import Local Footage` <kbd>CTRL</kbd> + <kbd>I</kbd> it ignores the first file on each folder.

![bug-importer](https://user-images.githubusercontent.com/10171059/55671747-a97f1880-5869-11e9-91c7-826fe9bc8bca.gif)

**Comment by NathanLovato** [comment] 2019-04-07 10:04
Is this blender 2.79? We don't support it anymore, you should work with blender 2.80 and a recent version of the plugin.

Then, if you have the same issue in the latest version, please go to the script editor/workspace and copy/paste the content of the JSON file that the operator stores there.

**Comment by NathanLovato** [comment] 2019-04-07 10:05
Note this never happened to me: I always use this operator to import all my footage. So it might have something to do with the file name? Anyway gotta see with the latest version of the addon as I changed some code in this operator

**Comment by henriiquecampos** [comment] 2019-04-08 13:50
Just tested in 2.8, the issue seems to be solved. Gonna update to it.

**Comment by henriiquecampos** [comment] 2019-04-17 14:30
Reopening this, it is still happening in 2.8 in the following .gif it skipped the first and second itens, and note it skipped the audio files for these as well

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/10171059/56296036-1c0eb480-6104-11e9-8e44-ed9828be1b32.gif)

**Comment by NathanLovato** [comment] 2019-04-17 23:06
I need reproducible steps, otherwise can't fix the bug. I've never had it here

**Comment by henriiquecampos** [comment] 2019-04-18 16:33
**Reproduction Steps**
1. Create a folder, e.g. `root`
1. Add `audio`, `image` and `video` folders
1. Create a .blend file and save in the `root` folder.
1. Add some, 10+, files to `video` and `audio` folders (.mp4 for video, .flac for audio)
1. Open the .blend file
1. Position the cursor at the frame `0`
1. Press <kbd>CTRL </kbd> + <kbd>I</kbd> to trigger the PowerSequencer `Import Local Footage`

---
Notes

Try naming the files with the following structure: `000 - File Name.extension`

**Comment by NathanLovato** [comment] 2019-04-18 20:37
I just needed what makes this bug happen reliably, the naming pattern in this case. Thanks, I'll check it out

On April 19, 2019 1:33:08 AM GMT+09:00, Henrique Campos <notifications@github.com> wrote:
>**Reproduction Steps**
>1. Create a folder, e.g. `root`
>1. Add `audio`, `image` and `video` folders
>1. Create a .blend file and save in the `root` folder.
>1. Add some, 10+, files to `video` and `audio` folders (.mp4 for video,
>.flac for audio)
>1. Open the .blend file
>1. Position the cursor at the frame `0`
>1. Press <kbd>CTRL </kbd> + <kbd>I</kbd> to trigger the PowerSequencer
>`Import Local Footage`
>
>---
>Notes
>
>Try naming the files with the following structure: `000 - File
>Name.extension`  
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/GDquest/Blender-power-sequencer/issues/344#issuecomment-484584017

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by NathanLovato** [comment] 2019-06-24 03:05
I just tested this, I don't have the problem. All video files get imported properly:

![Screenshot from 2019-06-24 12-03-19](https://user-images.githubusercontent.com/12694995/59988998-260ae180-9678-11e9-8daa-1a7e9cd7526f.png)

![Screenshot from 2019-06-24 12-03-51](https://user-images.githubusercontent.com/12694995/59988999-260ae180-9678-11e9-9f0a-ded45e68a47c.png)

16 input files, same naming scheme... does this still happen with the latest Blender 2.80 and latest power sequencer? If so, could you send me a project folder that has the issue? Import local footage mainly checks that the file is e.g. `video/**/*.video_ext` and that it's not in a `BL_proxy` folder, so there shouldn't be issues regardless of the name. I don't understand why it's happening - and why it's happening to you in particular.

**Comment by henriiquecampos** [comment] 2019-06-26 13:21
I'm doing it through the built-in workflow lately...I will try to test it out soon to see if I can get this again.

**Comment by NathanLovato** [comment] 2019-08-24 11:25
I rewrote import local footage, still couldn't reproduce the issue. Closing for now, please reopen if you still have it.

**Closed by NathanLovato** 2019-08-24 11:25 UTC
Labels: bug
