### ISSUE TITLE
Following a "Load Factory Settings" many menu items causes errors 

### ISSUE THREAD

**Issue by tin2tin** [GDquest/Blender-power-sequencer#266] opened 2018-10-26 18:09 UTC
After a fresh "Load Factory Settings" and try the menu items, many of them are throwing errors.  Ex. I started from the top of the menu:
Delete Direct: Error
Remove Gaps: Error
Border Select: Error
Select Linked Effect: Error
Deselect both options: Error
(And then I stopped... seems like a general check is missing?)

**Comment by NathanLovato** [comment] 2018-10-26 22:12
What are the errors you're talking?
Are you trying to use the operators on an empty sequencer after reloading factory settings? Which wouldn't make sense, but if I reload factory settings, activate power sequencer and add a strip to the sequencer there's no problem

**Comment by tin2tin** [comment] 2018-10-26 22:20
I'm not at my computer right now and can't see the exact wording. Don't you see any errors? It seems that some of the operators checks if the project has been saved and some do not, maybe those causing errors just needs that check? Or the check if the sequencer has been activated(by adding a strip)?

**Comment by NathanLovato** [comment] 2018-10-26 23:18
No errors if there's at least one strip on the sequencer - please take a screenshot of the tracebacks (python error popups) you get when you report an issue.

But if you get these errors only on an empty sequencer **and** after you reset to factory settings and reload PS (i.e. you don't save the settings and restart blender) I'd expect weird issues to pop up due to how we automate python loading. 

If you just want to test the addon on a fresh blender I'd invite you to work with a portable version instead where you can safely mess with the configuration - it's the kind of issue almost nobody will face and that would require a lot of work to fix and take a lot of time away from time-saving features and workflow improvements

**Comment by NathanLovato** [comment] 2018-11-04 05:41
Hey @tin2tin, any update on this issue? Is it still happening from the latest master? Razvan started to add some fix to an issue that happened only on Linux, it might be related.

**Comment by tin2tin** [comment] 2018-11-04 06:45
As mentioned in another issue, I can't install PS right now. The errors I mentioned above are when I "Load Factory Settings", install PS and use the PS menu(no strips added).  Some of the menu entries detect that the project hasn't been saved, but most of the gives the mentioned errors.  It is up to you if you think it is worth bothering with, I do understand " it's the kind of issue almost nobody will face".

**Comment by NathanLovato** [comment] 2018-11-05 00:07
What I'm saying is we can't begin investigating the bug without knowing what these errors are exactly. And I can't reproduce it here. I need screenshots or copies of the errors that appear in the console (Window menu -> Toggle System Console, you can copy and paste the text that appears there).

Could you please download the latest version, go through the steps again and share the errors with us? Also, you're on Windows 8, right?

**Comment by tin2tin** [comment] 2018-11-05 05:56
I haven't been all testing all menu entries, but here are some of the errors: 

Delete - Direct:
![image](https://user-images.githubusercontent.com/1322593/47980241-0d3cc400-e0c7-11e8-95b7-e2bff36765da.png)

Remove Gaps:
![image](https://user-images.githubusercontent.com/1322593/47980226-e9797e00-e0c6-11e8-94db-7badfc8afe4b.png)

Border Select:
![image](https://user-images.githubusercontent.com/1322593/47980282-407f5300-e0c7-11e8-8eb5-c2e2f98860d0.png)

Select Linked Effect:
![image](https://user-images.githubusercontent.com/1322593/47980317-64db2f80-e0c7-11e8-98da-8289654e1078.png)

Deselect both options:
![image](https://user-images.githubusercontent.com/1322593/47980347-86d4b200-e0c7-11e8-94cc-813f3b17a0b3.png)

Yes, I'm on Windows 8.

**Comment by NathanLovato** [comment] 2018-11-05 06:56
Thanks! 
So this only happens until you import footage, right? I think I see where this comes from - the menu options should be disabled until you add at least one strip to the sequencer, or select a strip, depending on the case. I think it's because I used a template to write tools for a while and didn't change the `poll` method on these operators 😅

**Comment by NathanLovato** [comment] 2018-11-05 07:10
Actually no, it doesn't make sense. And I can't reproduce these. You shouldn't even be able to click on Delete direct or to call it if there's no sequence on the VSE. On my end the options are properly greyed out, even after a reset:

![image](https://user-images.githubusercontent.com/12694995/47982985-22404400-e115-11e8-8125-010f811b8062.png)

I don't understand... @razcore-art could you give this a try (do a factory reset)?

**Comment by NathanLovato** [comment] 2018-11-05 07:12
By the way @tin2tin you should be able to safely use Power Sequencer without doing a factory reset: like many other add-ons, it removes all the shortcuts it adds when you quit blender or you deactivate it.

**Comment by NathanLovato** [comment] 2018-11-05 11:56
Oh, so then it's always happening? I really don't get it, it doesn't happen here. A Windows 8 specific bug maybe? Are you on Blender 2.79b?

**Comment by NathanLovato** [comment] 2018-11-20 00:36
Razvan and I added some commits to clean up errors. When you have a moment, could you give me an update on this issue? Do you still get the same errors?

**Comment by NathanLovato** [comment] 2018-11-20 22:37
Ah okay so that's because in a factory Blend file, selected_sequences is None? I'm working with a different template to edit videos so the list has already been initialized.
I wondered why this other addon had this ".. is not None" check many poll operator, got it 😄

**Comment by NathanLovato** [comment] 2019-03-26 14:32
I don't have the error anymore in Blender 2.80, with the latest version of Power Sequencer. Closing for now.

**Closed by NathanLovato** 2019-03-26 14:32 UTC
Labels: bug
