### ISSUE TITLE
BPSRender resulting an error

### ISSUE THREAD

**Issue by damarindra** [GDquest/Blender-power-sequencer#307] opened 2019-01-03 04:17 UTC
```
bpsrender D:\vid\Hexo\_1.blend
» Probing...
» Input(blend) @ D:\vid\Hexo\_1.blend...
Traceback (most recent call last):
  File "c:\python\python3.6.5\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python\python3.6.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python3.6.5\Scripts\bpsrender.exe\__main__.py", line 9, in <module>
  File "c:\python\python3.6.5\lib\site-packages\bpsrender\__main__.py", line 122, in main
    cmds, kwargs = setup(C, clargs)
  File "c:\python\python3.6.5\lib\site-packages\bpsrender\setup.py", line 171, in setup
    setups_f, {}))
  File "c:\python\python3.6.5\lib\site-packages\bpsrender\setup.py", line 170, in <lambda>
    kwargs = dict(reduce(lambda acc, sf: {**acc, **sf(cfg, clargs, **acc)},
  File "c:\python\python3.6.5\lib\site-packages\bpsrender\setup.py", line 61, in setup_probe
    **kwargs)
  File "c:\python\python3.6.5\lib\site-packages\bpsrender\calls.py", line 391, in call
    out = calls[cmds[0]](cfg, clargs, cmds[1], **kwargs)
  File "c:\python\python3.6.5\lib\site-packages\bpsrender\calls.py", line 110, in call_probe
    frame_start, frame_end, ext = chain(*tmp)
ValueError: not enough values to unpack (expected 3, got 0)
```
I've been using bpsrender quite a lot and without any error. And this issue just appears somehow. It is quite weird about what happened, but right now, I can't use bpsrender anymore.

Below is running with --dry-run

```
bpsrender D:\vid\Hexo\1.blend -w 24 --dry-run
DEBUG:BPS:CMD-PROBE: blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\probe.py --disable-autoexec


» Probing...
» Input(blend) @ D:\vid\Hexo\1.blend...
• Probing done.
INFO:BPS:Setup:
INFO:BPS:probe_py_normalized: c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\probe.py
INFO:BPS:mixdown_py_normalized: c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\mixdown.py
INFO:BPS:video_py_normalized: c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py
INFO:BPS:frame_start: 0
INFO:BPS:frame_end: 0
INFO:BPS:frames_total: 1
INFO:BPS:ext:
INFO:BPS:render_path: C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy
INFO:BPS:render_parts_path: C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender
INFO:BPS:chunks_file_path: C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\chunks.txt
INFO:BPS:render_chunk_path: C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_#######
INFO:BPS:render_video_path: C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_v
INFO:BPS:render_mixdown_path: C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_m.flac
INFO:BPS:render_audiovideo_path: C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\1
DEBUG:BPS:CMD-MIXDOWN: blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\mixdown.py --disable-autoexec -- C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_m.flac

» Rendering mixdown...
» Output @ C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_m.flac...
• Mixdown done.
DEBUG:BPS:CMD-VIDEO:
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0--1): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e -1 --render-anim
DEBUG:BPS:CMD-CHUNK(0-0): blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\video.py --disable-autoexec --render-output C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_####### -s 0 -e 0 --render-anim

» Rendering video (w/o audio)...
» Output @ C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_c_#######...
INFO:BPS:CALL-VIDEO: generating C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\chunks.txt
  0%|                                                                                                                             | 0/1 [00:00<?, ?frames/s]• Video chunks rendering done.

DEBUG:BPS:CMD-CONCATENATE: ffmpeg -stats -f concat -safe -0 -i C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\chunks.txt -c copy -y C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_v

» Concatenating (video) chunks...
» Output @ C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_v...
• Concatenating done.
DEBUG:BPS:CMD-JOIN: ffmpeg -stats -i C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_v -i C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\bpsrender\1_m.flac -map 0:v:0 -c:v copy -map 1:a:0 -c:a aac -b:a 192k -y C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\1

» Joining audio/video...
» Output @ C:\Users\Damar Indra\Apps\power-sequencer\scripts\BPSProxy\1...
• Joining done.
```

**Comment by NathanLovato** [comment] 2019-01-03 06:40
Did you set your render path and settings in Blender? It's failing at the very first step, when it tries to get the length of your video:

```
INFO:BPS:frame_start: 0
INFO:BPS:frame_end: 0
INFO:BPS:frames_total: 1
INFO:BPS:ext:
```

Also you're using Blender 2.79 right? I haven't tried 2.8 yet, not sure if it could work, but we don't support it at the moment.

**Comment by razcore-art** [comment] 2019-01-03 06:45
So yes, first thing is I'm not sure if this works with blender 2.8. Haven't checked, most likely there's problems at later steps if not at the very first.

frames start/end are supposed to be 0 here cause we're using `--dry-run`, that's fine.

@damarindra can you paste the output of `blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\probe.py --disable-autoexec`? This is what BPSRender uses to get some info from blender.

**Comment by damarindra** [comment] 2019-01-03 06:51
Using blender 2.79 and this settings
![image](https://user-images.githubusercontent.com/8519218/50626009-52159780-0f5e-11e9-902f-41461d51567b.png)

The error is quite weird IMO. So I rendering about 10 videos with `bpsrender 1.blend -w 24 && bpsrender 2.blend -w 24 && so on` command, so it will automatically render the next video. After about 3 successful rendered video, I've got that error message. I've tried to change the video name without any space, no luck. Logically, if I render blend file with success result, it must be work right? but no, I can't render with bpsrender anymore 😢 .

Here is the output running `blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\probe.py --disable-autoexec`
```
blender --background D:\vid\Hexo\1.blend --python c:\python\python3.6.5\lib\site-packages\bpsrender\bscripts\probe.py --disable-autoexec
Read prefs: C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
Exception in module register(): 'C:\\Users\\Damar Indra\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\b_painter\\__init__.py'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\__init__.py", line 135, in register
    register_keymaps()
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\__init__.py", line 91, in register_keymaps
    km = addon.keymaps.new(name = "Image Paint", space_type = "EMPTY")
AttributeError: 'NoneType' object has no attribute 'keymaps'
Exception in module register(): 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\space_view3d_brush_menus\\__init__.py'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\space_view3d_brush_menus\__init__.py", line 115, in register
    km = wm.keyconfigs.addon.keymaps.new(name=mode)
AttributeError: 'NoneType' object has no attribute 'keymaps'
Exception in module register(): 'C:\\Program Files\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\object_boolean_tools.py'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\object_boolean_tools.py", line 1451, in register
    km = wm.keyconfigs.addon.keymaps.new(name='Object Mode')
AttributeError: 'NoneType' object has no attribute 'keymaps'
Imported multifiles
_______REgister previews
.. .ao
.. .ao_legacy
.. .bevel_mask
.. .cavity
.. .curvature
.. .diffuse
.. .displacment
.. .dust
.. .id_element
.. .id_material
.. .normal_object
.. .normal_object_bevel
.. .normal_tangent
.. .normal_tangent_bevel
.. .paint_base
.. .position
.. .selection
.. .wireframe
Exception in module register(): 'C:\\Users\\Damar Indra\\AppData\\Roaming\\Blender Foundation\\Blender\\2.79\\scripts\\addons\\power-sequencer\\__init__.py' Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 350, in enable
    mod.register()
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\power-sequencer\__init__.py", line 80, in register
    keymaps = register_shortcuts()
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\power-sequencer\utils\register_shortcuts.py", line 40, in register_shortcuts
    km = wm.keyconfigs.addon.keymaps.new(name=name, space_type=keymaps_meta[name])
AttributeError: 'NoneType' object has no attribute 'keymaps'
Read blend: D:\vid\Hexo\1.blend
Traceback (most recent call last):
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\bpainter_properties.py", line 397, in set_hotkeys
    keymap = bpy.context.window_manager.keyconfigs.addon.keymaps['Image Paint']
KeyError: 'bpy_prop_collection[key]: key "Image Paint" not found'
File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\bpainter_properties.py", line 396, in set_hotkeys
Error: Traceback (most recent call last):
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\operators\preset_handling.py", line 254, in execute
    brush_data_user = load_brush_data(presets_user_path)
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\operators\preset_handling.py", line 159, in load_brush_data
    data = json.load(data_file)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1032 column 28 (char 23613)

location: C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py:189

Traceback (most recent call last):
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\operators\preset_handling.py", line 254, in execute
    brush_data_user = load_brush_data(presets_user_path)
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\operators\preset_handling.py", line 159, in load_brush_data
    data = json.load(data_file)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1032 column 28 (char 23613)

location: C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py:189

location: C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py:189
Error: Traceback (most recent call last):
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\operators\preset_handling.py", line 254, in execute
    brush_data_user = load_brush_data(presets_user_path)
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\operators\preset_handling.py", line 159, in load_brush_data
    data = json.load(data_file)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\liTraceback (most recent call last):
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\__init__.py", line 185, in start_modal_update
    bpy.ops.b_painter.import_brush_from_json(all_brushes=True)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\operators\preset_handling.py", line 254, in execute
    brush_data_user = load_brush_data(presets_user_path)
  File "C:\Users\Damar Indra\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\b_painter\operators\preset_handling.py", line 159, in load_brush_data
    data = json.load(data_file)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Blender Foundation\Blender\2.79\python\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 1032 column 28 (char 23613)

location: C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py:189


... truncatedBPS:1 75397 .mp4

Blender quit
```

**Comment by razcore-art** [comment] 2019-01-03 06:57
That's interesting, I've never seen this output from blender before. The problem is near the last line: `... truncatedBPS:1 75397 .mp4`, don't know why `... truncated` is there, but that's the problem, it's a simple fix, I'll push it shortly.

**Comment by razcore-art** [comment] 2019-01-03 07:01
OK @damarindra, I just pushed the fix, it should work after you update. So I'm closing this issue, we'll just reopen if there's more to it.

**Closed by razcore-art** 2019-01-03 07:01 UTC

**Comment by damarindra** [comment] 2019-01-03 07:44
yuhuu, it works!! thanks!!

**Comment by razcore-art** [comment] 2019-01-03 08:49
yay :raised_hands:
