### ISSUE TITLE
Powersequencer crashes blender on commandline rendering - cannot be disabled without crashing blender

### ISSUE THREAD

**Issue by acebone** [GDQuest/blender-power-sequencer#456] opened 2021-10-16 12:41 UTC
**I'm submitting a...**

- [x] Bug report.
- [ ] Feature request.

## Bug report ##

Blender 2.93.4

**What is the current behavior?**

When trying to render headless from the command-line, blender crashes immediately

Also: PowerSequencer crashes blender when you try to deactivate it

**What is the expected behavior?**

The headless rendering should just proceed

Deactivation should just deactivate the addon

**Tell us the steps to reproduce the bug, and if possible share a minimal demo of the problem.** 

From a blank startup-file go to edit->preferences->addons - locate Power Sequence. Disable it - blender crashes (without disabling it) - in /tmp/blender.crash.text the output is

> \# Blender 2.93.4, Commit date: 2021-08-31 09:23, Hash b7205031cec4
bpy.data.window_managers["WinMan"].addon_search = "power"  # Property

\# backtrace
blender(BLI_system_backtrace+0x20) [0xa593390]
blender() [0xf5faed]
/lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fa4a6bf8210]
[0x7fa4649ba8f0]

\# Python backtrace

Any scene I try to render from commandline gives this error

> Blender 2.93.4 (hash b7205031cec4 built 2021-08-31 23:43:17)
Read prefs: /home/esm/.config/blender/2.93/config/userpref.blend
Exception in module register(): /home/esm/src/blender/blender-2.93.4-linux-x64/2.93/scripts/addons/power_sequencer/__init__.py
Traceback (most recent call last):
  File "/home/esm/src/blender/blender-2.93.4-linux-x64/2.93/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/home/esm/src/blender/blender-2.93.4-linux-x64/2.93/scripts/addons/power_sequencer/__init__.py", line 76, in register
    bpy.utils.register_tool(cls, after=last_tool, separator=index == 0)
  File "/home/esm/src/blender/blender-2.93.4-linux-x64/2.93/scripts/modules/bpy/utils/__init__.py", line 888, in register_tool
    tool_converted = tool_from_class(tool_cls)
  File "/home/esm/src/blender/blender-2.93.4-linux-x64/2.93/scripts/modules/bpy/utils/__init__.py", line 885, in tool_from_class
    cls._km_action_simple(kc_default, kc, context_descr, tool_def.label, keymap_data)
  File "/home/esm/src/blender/blender-2.93.4-linux-x64/2.93/scripts/startup/bl_ui/space_toolsystem_common.py", line 471, in _km_action_simple
    km = kc.keymaps.get(km_idname)
AttributeError: 'NoneType' object has no attribute 'keymaps'
vseqf updater verbose is enabled
vseqf Updater: Read in JSON settings from file
Exception in module register(): /home/esm/.config/blender/2.93/scripts/addons/VSE_Transform_Tools/__init__.py
Traceback (most recent call last):
  File "/home/esm/src/blender/blender-2.93.4-linux-x64/2.93/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/home/esm/.config/blender/2.93/scripts/addons/VSE_Transform_Tools/__init__.py", line 456, in register
    km = wm.keyconfigs.addon.keymaps.new(name="SequencerPreview", space_type="SEQUENCE_EDITOR", region_type="WINDOW")
AttributeError: 'NoneType' object has no attribute 'keymaps'
Error: Cannot render, no camera
Read blend: /home/esm/doku/alt/storyboard-hf_pilotprojekt_files/blender/marianna-limer-støvle.blend
Exception in module unregister(): '/home/esm/.config/blender/2.93/scripts/addons/VSEQF-master/__init__.py'
Traceback (most recent call last):
  File "/home/esm/src/blender/blender-2.93.4-linux-x64/2.93/scripts/modules/addon_utils.py", line 438, in disable
    mod.unregister()
  File "/home/esm/.config/blender/2.93/scripts/addons/VSEQF-master/__init__.py", line 1608, in unregister
    keymapitems = bpy.context.window_manager.keyconfigs.addon.keymaps['Sequencer'].keymap_items
KeyError: 'bpy_prop_collection[key]: key "Sequencer" not found'

## Feature request ##

**Describe the problem you're trying to solve.**

**Tell us which solutions you've explored, the solution you would pick, and why you think it would be the best for everyone.**

## Other ##

**Other information**

**Comment by NathanLovato** [comment] 2021-10-16 15:09
Have you tried 2.93.5? It might be a bug in 2.93.4 because I can't reproduce the issue with the latest bugfix version.

**Comment by acebone** [comment] 2021-10-17 09:58
I don't know what was at play. All of a sudden I could de-register with no problems, and I can also render from commandline now. It does the render and then it says:

> Exception in module unregister(): '/home/esm/.config/blender/2.93/scripts/addons/VSEQF-master/__init__.py'
> Traceback (most recent call last):
>   File "/home/esm/src/blender/blender-2.93.4-linux-x64/2.93/scripts/modules/addon_utils.py", line 438, in disable
>     mod.unregister()
>   File "/home/esm/.config/blender/2.93/scripts/addons/VSEQF-master/__init__.py", line 1608, in unregister
>     keymapitems = bpy.context.window_manager.keyconfigs.addon.keymaps['Sequencer'].keymap_items
> KeyError: 'bpy_prop_collection[key]: key "Sequencer" not found'
> 
> Blender quit
> 

Something seems to be amiss, but I'm not sure where the fault is exactly.

**Comment by NathanLovato** [comment] 2021-10-17 13:42
Could you please try to update to the latest Blender bugfix version? If that addresses the issue, then it's not a bug on the side of power sequencer and we can close this.

**Comment by acebone** [comment] 2021-10-21 13:14
Will do ASAP ...

**Comment by NathanLovato** [comment] 2022-06-15 18:53
No update since last year, closing the report as we can't reproduce the issue

**Closed by NathanLovato** 2022-06-15 18:53 UTC
