### ISSUE TITLE
Let Mouse Trim with and without gap operate on same selections

### ISSUE THREAD

**Issue by DocoDan** [GDquest/Blender-power-sequencer#241] opened 2018-09-13 13:06 UTC
Mouse trim (right click and drag) seems to affect only the present channel under cursor, while Mouse trim and close gap (right click + shift and drag) seems to affect all channels under the cursor.
Can you confirm?
I guess it would be more convenient if close gap would affect only the channel under the cursor, too.

You can see here:
http://www.hotbytedog.w4f.eu/pic/PoweSeq.gif

**Comment by NathanLovato** [comment] 2018-09-13 22:42
Yes, Duplicate of #123

**Closed by NathanLovato** 2018-09-13 22:42 UTC
