### ISSUE TITLE
Clear fades error

### ISSUE THREAD

**Issue by javimixet** [GDquest/Blender-power-sequencer#296] opened 2018-12-07 02:36 UTC
When trying to clear fades from strip I get this error:
```
Traceback (most recent call last):
  File "/home/ii/.config/blender/2.79/scripts/addons/Blender-power-sequencer-master/operators/fade_clear.py", line 38, in execute
    if strip == eval(curve.data_path.replace('.blend_alpha', '')):
  File "<string>", line 1, in <module>
NameError: name 'sequence_editor' is not defined

location: <unknown location>:-1
```

Blender 2.79b
Hash: f4dc9f9d68b

**Comment by NathanLovato** [comment] 2019-01-03 06:59
I couldn't reproduce the bug and without more info, I can't fix it. Please reopen the issue if you can provide more info

**Comment by Calinou** [comment] 2019-03-14 22:07
I can reproduce this on Blender 2.79 with Power Sequencer 1.2.0:

![image](https://user-images.githubusercontent.com/180032/54394658-d34f8000-46ad-11e9-8fbe-7089c0154c94.png)

Other fade-related operations work correctly.

**Comment by javimixet** [comment] 2019-03-15 00:46
I'm also still getting the error. In the file attached when trying to clear fades from the strip.
[example_file.blend.zip](https://github.com/GDquest/Blender-power-sequencer/files/2968949/example_file.blend.zip)
The file is the default, I add the strip, press "f" and fades are added, press "ctrl+alt+f" and get the error. I've tried a couple versions of 2.79 and I'm getting the error in all of them.
Tell me what other kind of additional info can I provide.

**Comment by NathanLovato** [comment] 2019-03-15 07:28
I could reproduce it this time, it's fixed in the latest master!

**Comment by NathanLovato** [comment] 2019-03-15 07:28
(NB: Blender 2.80 only now)

**Comment by NathanLovato** [comment] 2019-03-15 07:29
@Calinou nice to see you here as well! Do you use the add-on? :)

**Closed** 2019-03-15 07:28 UTC
Labels: bug
